name: porto_seguro_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - notebook
  - ipykernel
  - missingno
  - lightgbm
  - xgboost
  - tensorflow
  - scikeras
  - category_encoders